- name: Demo on vars
  hosts: localhost
  vars:
    URL: play.google.com
  tasks:
    - name: Print Play level variable
      ansible.builtin.debug:
        msg: URL = {{ URL }}

    - name: Print variable declared in tasks
      vars:
        URL: task.google.com
        ansible.builtin.debug:
          msg: URL = {{ URL }}

  roles:
    - demo