- name: loops
  hosts: localhost
  tasks:
    - name: Loop Demo
      ansible.builtin.debug:
        msg: Hello, {{ item }}
      loop:
        - Karan
        - Rohan
        - Deeksha

    - name: Loop Demo 2
      ansible.builtin.debug:
        msg: Hello, {{ item.name }}. Age of Yours is {{ item.age }} years.
      loop:
        - { name: "Karan", age: 21, run: true }
        - { name: "Deeksha", age: 32, run: true }
        - { name: "Rohan", age: 36, run: false }
      when: item.run